import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowRight, BarChart3, CheckCircle2, ExternalLink, LockKeyhole, QrCode, RefreshCw, ScanLine, ShieldCheck } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import toast from 'react-hot-toast'
import api from '@/lib/axios'
import { GRUPOS_MODULOS, MODULOS_PLATAFORMA, planNormalizado, type GrupoModulo, type ModuloPlataforma } from '@/config/modules.config'
import { useAuth } from '@/contexts/AuthContext'

const nombresPlan: Record<string,string> = { free:'FREE', pro:'PRO', enterprise:'ENTERPRISE / WMS' }
const resumenGrupo: Record<GrupoModulo,string> = {
  Operacion:'Ventas, caja, pedidos, clientes, compras y proveedores.',
  'Puestos y atencion':'Mesas, reservas, agenda, responsables y promociones.',
  'Inventario y WMS':'Inventario, kardex, bodegas, conteos y traslados.',
  'Restaurante y recetas':'Recetas, ingredientes, costos, mermas y produccion.',
  Administracion:'Usuarios, permisos, reportes, auditoria e integraciones.',
  Sistema:'Configuracion, soporte, salud y actualizaciones.',
}

export default function RootPage() {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const { startSupport } = useAuth()
  const [empresaId, setEmpresaId] = useState(''); const [grupoActivo,setGrupoActivo]=useState<GrupoModulo>('Operacion'); const [busqueda,setBusqueda]=useState('')
  const { data: empresas = [] } = useQuery({ queryKey:['sa-empresas'], queryFn:async()=>{ const {data}=await api.get<any>('/superadmin/empresas'); return data.data||data } })
  const { data: extras = [] } = useQuery({ queryKey:['sa-root-extras'], queryFn:async()=>{ const {data}=await api.get<any>('/superadmin/root'); return data.data?.extras||[] } })
  const empresa = empresas.find((item:any)=>item.id===empresaId)
  const extrasEmpresa = useMemo(()=>new Set(extras.filter((item:any)=>item.empresa_id===empresaId&&item.activo).map((item:any)=>item.modulo_id)),[extras,empresaId])
  const habilitado = (modulo:ModuloPlataforma) => !!empresa && modulo.disponible && (modulo.planes.includes(planNormalizado(empresa.plan)) || extrasEmpresa.has(modulo.id)) && (!modulo.negocios || modulo.negocios.includes(String(empresa.tipo||'').toLowerCase()))
  const abrirModulo = useMutation({ mutationFn: async (modulo:ModuloPlataforma) => { if(!empresaId) throw new Error('Selecciona primero una empresa cliente'); if(!modulo.ruta||!modulo.disponible) throw new Error('Este modulo esta en preparacion'); if(!habilitado(modulo)) throw new Error('Este modulo no esta incluido para la empresa seleccionada'); await startSupport(empresaId); return modulo.ruta }, onError:(error:any)=>toast.error(error?.message||'No fue posible abrir el modulo') })
  const cambiarExtra = useMutation({ mutationFn:({moduloId,activo}:{moduloId:string;activo:boolean})=>api.patch('/superadmin/root',{empresa_id:empresaId,modulo_id:moduloId,activo}), onSuccess:()=>queryClient.invalidateQueries({queryKey:['sa-root-extras']}), onError:(e:any)=>toast.error(e?.response?.data?.msg||'No se pudo actualizar el modulo extra') })
  const modulosGrupo=MODULOS_PLATAFORMA.filter(modulo=>modulo.grupo===grupoActivo&&modulo.nombre.toLowerCase().includes(busqueda.toLowerCase()))
  const modulosHabilitados=empresa?MODULOS_PLATAFORMA.filter(habilitado).length:0
  const modulosDisponibles=MODULOS_PLATAFORMA.filter(modulo=>modulo.disponible).length
  return <div className="space-y-4">
    <header className="flex flex-col gap-4 border-b border-white/10 pb-4 xl:flex-row xl:items-center"><div className="min-w-0 flex-1"><p className="text-xs text-surface-200/50">Inicio / Panel principal</p><h1 className="mt-1 text-2xl font-bold text-surface-50">Bienvenido, Super Administrador</h1><p className="text-sm text-surface-200/60">Centro de control de StockFlow POS.</p></div><div className="flex flex-wrap items-center gap-2"><input className="input h-11 min-w-[220px]" value={busqueda} onChange={event=>setBusqueda(event.target.value)} placeholder="Buscar modulo"/><select className="input h-11 min-w-[230px]" value={empresaId} onChange={event=>setEmpresaId(event.target.value)}><option value="">Seleccionar empresa</option>{empresas.map((item:any)=><option key={item.id} value={item.id}>{item.nombre} - {item.plan||'basico'}</option>)}</select><button className="btn-secondary min-h-11" onClick={()=>queryClient.invalidateQueries({queryKey:['sa-empresas']})}><RefreshCw className="h-4 w-4"/>Actualizar</button></div></header>
    <div className="grid gap-4 xl:grid-cols-[250px_minmax(0,1fr)]"><aside className="space-y-3"><div className="overflow-hidden rounded-lg border border-white/10 bg-surface-800/80">{GRUPOS_MODULOS.map(grupo=>{const Icon=MODULOS_PLATAFORMA.find(m=>m.grupo===grupo)?.icono||ShieldCheck; const activo=grupo===grupoActivo; return <button key={grupo} type="button" onClick={()=>{setGrupoActivo(grupo);setBusqueda('')}} className={`flex min-h-[82px] w-full items-center gap-3 border-b border-white/10 px-4 py-3 text-left last:border-b-0 ${activo?'bg-brand-500/15':'hover:bg-white/5'}`}><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg ${activo?'bg-brand-500 text-white':'bg-surface-700 text-brand-300'}`}><Icon className="h-5 w-5"/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-surface-50">{grupo}</span><span className="mt-1 block text-xs leading-5 text-surface-200/55">{resumenGrupo[grupo]}</span></span><ArrowRight className="h-4 w-4 text-surface-200/45"/></button>})}</div><div className="rounded-lg border border-white/10 bg-surface-800/60 p-4"><p className="text-xs text-surface-200/55">Plan actual</p><p className="mt-2 inline-flex rounded bg-brand-500/25 px-2 py-1 text-xs font-semibold text-brand-200">{empresa?nombresPlan[planNormalizado(empresa.plan)]:'Selecciona empresa'}</p><div className="my-4 border-t border-white/10"/><p className="text-sm font-medium text-surface-50">Modulos habilitados</p><p className="mt-1 text-2xl font-bold text-surface-50">{modulosHabilitados} <span className="text-sm font-normal text-surface-200/45">/ {modulosDisponibles}</span></p><div className="mt-2 h-2 overflow-hidden rounded bg-surface-900"><div className="h-full rounded bg-emerald-400" style={{width:`${modulosDisponibles?Math.round(modulosHabilitados/modulosDisponibles*100):0}%`}}/></div><button type="button" onClick={()=>document.getElementById('matriz-planes')?.scrollIntoView({behavior:'smooth'})} className="mt-4 text-sm text-brand-300 hover:text-brand-200">Ver matriz de planes <ExternalLink className="ml-1 inline h-3.5 w-3.5"/></button></div></aside>
      <main className="min-w-0 space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{label:'Empresas activas',value:empresas.filter((e:any)=>e.activa).length,icon:CheckCircle2,color:'text-emerald-300',bg:'bg-emerald-500/15'},{label:'Modulos disponibles',value:modulosDisponibles,icon:BarChart3,color:'text-brand-300',bg:'bg-brand-500/15'},{label:'Escanear QR',value:'Abrir',icon:QrCode,color:'text-cyan-300',bg:'bg-cyan-500/15',ruta:'/app/escanear/qr'},{label:'Escanear codigo',value:'Abrir',icon:ScanLine,color:'text-sky-300',bg:'bg-sky-500/15',ruta:'/app/escanear/barras'}].map(item=>{const Icon=item.icon; return <button key={item.label} type="button" disabled={!item.ruta||!empresaId} onClick={()=>item.ruta&&abrirModulo.mutate({id:item.ruta.includes('qr')?'qr':'barras',nombre:item.label,grupo:'Inventario y WMS',icono:Icon,ruta:item.ruta,planes:['pro','enterprise'],disponible:true,descripcion:'Inventario'})} className="card flex min-h-24 items-center gap-3 p-4 text-left disabled:opacity-60"><span className={`flex h-11 w-11 items-center justify-center rounded-lg ${item.bg}`}><Icon className={`h-6 w-6 ${item.color}`}/></span><span><span className="block text-xs text-surface-200/55">{item.label}</span><span className="mt-1 block text-xl font-bold text-surface-50">{item.value}</span></span></button>})}</div>
        <section className="card p-4"><div className="mb-4 flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-surface-50">{grupoActivo}</h2><p className="mt-1 text-sm text-surface-200/60">{resumenGrupo[grupoActivo]}</p></div>{empresa?<span className="badge-green">Empresa: {empresa.nombre}</span>:<span className="badge-gray">Selecciona una empresa para abrir</span>}</div><div className="grid gap-3 md:grid-cols-2 2xl:grid-cols-3">{modulosGrupo.map(modulo=>{const Icon=modulo.icono; const listo=habilitado(modulo); return <article key={modulo.id} className="flex min-h-44 flex-col rounded-lg border border-white/10 bg-surface-900/35 p-4"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-brand-500/15"><Icon className="h-6 w-6 text-brand-300"/></span><div className="min-w-0"><h3 className="font-semibold text-surface-50">{modulo.nombre}</h3><p className="mt-1 text-sm leading-6 text-surface-200/60">{modulo.descripcion}</p></div></div><div className="mt-auto flex items-center justify-between gap-2 pt-4"><span className={`text-xs ${listo?'text-emerald-300':'text-surface-200/40'}`}>{!modulo.disponible?'Proximamente':listo?'Disponible':'Bloqueado por plan'}</span><button type="button" disabled={!listo||abrirModulo.isPending} onClick={()=>abrirModulo.mutate(modulo)} className="btn-secondary min-h-11 disabled:opacity-45">Entrar <ArrowRight className="h-4 w-4"/></button></div></article>})}{modulosGrupo.length===0&&<p className="py-10 text-center text-surface-200/45">No hay modulos que coincidan con la busqueda.</p>}</div></section>
      </main></div>
    <section id="matriz-planes" className="card overflow-hidden"><div className="border-b border-white/10 px-4 py-3"><h2 className="text-sm font-semibold uppercase tracking-wide text-surface-50">Modulos extra y matriz de planes</h2></div>{empresaId&&<div className="border-b border-white/10 p-4"><p className="mb-3 text-sm text-surface-200/65">Activa como extra solo modulos que ya tengan pantalla funcional para esta empresa.</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{MODULOS_PLATAFORMA.filter(modulo=>modulo.disponible&&(!modulo.negocios||modulo.negocios.includes(String(empresa?.tipo||'').toLowerCase()))).map(modulo=>{const incluido=modulo.planes.includes(planNormalizado(empresa?.plan));const extra=extrasEmpresa.has(modulo.id);return <label key={modulo.id} className="flex min-h-11 items-center gap-2 rounded border border-white/10 px-3 text-sm"><input type="checkbox" checked={incluido||extra} disabled={incluido||cambiarExtra.isPending} onChange={event=>cambiarExtra.mutate({moduloId:modulo.id,activo:event.target.checked})}/><span className="flex-1">{modulo.nombre}</span><span className="text-xs text-surface-200/45">{incluido?'Incluido':extra?'Extra':''}</span></label>})}</div></div>}<div className="overflow-x-auto"><table className="table-base"><thead><tr><th>Modulo</th><th>FREE</th><th>PRO</th><th>ENTERPRISE / WMS</th><th>Extra</th></tr></thead><tbody>{MODULOS_PLATAFORMA.filter(modulo=>modulo.disponible).map(modulo=><tr key={modulo.id}><td className="font-medium">{modulo.nombre}</td>{(['free','pro','enterprise'] as const).map(plan=><td key={plan}>{modulo.planes.includes(plan)?<span className="text-emerald-300">Disponible</span>:'-'}</td>)}<td>{modulo.planes.length<3?'Activable':'Incluido'}</td></tr>)}</tbody></table></div></section>
  </div>
}
