export const TIPOS_NEGOCIO = [
  { value: 'tienda', label: 'Tienda' },
  { value: 'tienda_bar', label: 'Tienda Bar' },
  { value: 'tienda_ropa', label: 'Tienda de ropa' },
  { value: 'tienda_calzado', label: 'Tienda de calzado' },
  { value: 'tienda_ropa_calzado', label: 'Tienda de ropa y calzado' },
  { value: 'minimercado', label: 'Minimercado' },
  { value: 'supermercado', label: 'Supermercado' },
  { value: 'tienda_abarrotes', label: 'Tienda de abarrotes' },
  { value: 'licorera', label: 'Licorera' },
  { value: 'papeleria', label: 'Papeleria' },
  { value: 'drogueria', label: 'Drogueria' },
  { value: 'tienda_mascotas', label: 'Tienda de mascotas' },
  { value: 'tienda_tecnologia', label: 'Tienda de tecnologia' },
  { value: 'tienda_hogar', label: 'Tienda de hogar' },
  { value: 'legumbreria', label: 'Legumbreria' },
  { value: 'carniceria', label: 'Carniceria' },
  { value: 'pescaderia', label: 'Pescaderia' },
  { value: 'fruver', label: 'Fruver' },
  { value: 'ferreteria', label: 'Ferreteria' },
  { value: 'panaderia', label: 'Panaderia' },
  { value: 'reposteria', label: 'Reposteria' },
  { value: 'restaurante', label: 'Restaurante' },
  { value: 'restaurante_bar', label: 'Restaurante Bar' },
  { value: 'cafeteria', label: 'Cafeteria' },
  { value: 'heladeria', label: 'Heladeria' },
  { value: 'pasteleria', label: 'Pasteleria' },
  { value: 'comidas_rapidas', label: 'Comidas rapidas' },
  { value: 'bar', label: 'Bar' },
  { value: 'discoteca', label: 'Discoteca' },
  { value: 'bar_discoteca', label: 'Bar y discoteca' },
  { value: 'barberia', label: 'Barberia' },
  { value: 'salon_belleza', label: 'Salon de belleza' },
  { value: 'spa', label: 'Spa' },
  { value: 'estetica', label: 'Estetica' },
  { value: 'manicure', label: 'Manicure y unas' },
  { value: 'lavanderia', label: 'Lavanderia' },
  { value: 'taller', label: 'Taller automotriz' },
  { value: 'otro', label: 'Otro comercio o servicio' },
] as const
