import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link2, Plus, Plug, Trash2 } from 'lucide-react'
import api from '@/lib/axios'
import { PageLoader } from '@/components/ui/Spinner'
import Modal from '@/components/ui/Modal'
import toast from 'react-hot-toast'

const proveedores = ['siigo','contai','alegra','quickbooks','otro']

export default function IntegracionesPage() {
  const qc = useQueryClient()
  const [abierto,setAbierto] = useState(false)
  const [form,setForm] = useState({proveedor:'siigo',nombre:'Siigo',ambiente:'pruebas',endpoint:'',usuario:'',secreto:'',activo:false})
  const { data: integraciones = [], isLoading } = useQuery({queryKey:['integraciones-erp'],queryFn:async()=>{const {data}=await api.get<any>('/integraciones'); return data.data || data}})
  const crear = useMutation({mutationFn:()=>api.post('/integraciones',form),onSuccess:()=>{qc.invalidateQueries({queryKey:['integraciones-erp']});setAbierto(false);toast.success('Integracion guardada')},onError:(e:any)=>toast.error(e?.response?.data?.msg ?? 'No se pudo guardar')})
  const actualizar = useMutation({mutationFn:({id,activo}:{id:string;activo:boolean})=>api.patch(`/integraciones/${id}`,{activo}),onSuccess:()=>qc.invalidateQueries({queryKey:['integraciones-erp']}),onError:()=>toast.error('No se pudo actualizar')})
  const eliminar = useMutation({mutationFn:(id:string)=>api.delete(`/integraciones/${id}`),onSuccess:()=>{qc.invalidateQueries({queryKey:['integraciones-erp']});toast.success('Integracion eliminada')}})
  if (isLoading) return <PageLoader/>
  return <div className="space-y-5">
    <div className="page-header"><div><h1 className="page-title">Integraciones ERP</h1><p className="page-subtitle">Conecta la facturacion y contabilidad del negocio con plataformas externas.</p></div><button className="btn-primary btn-sm" onClick={()=>setAbierto(true)}><Plus className="w-4 h-4"/>Nueva integracion</button></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{integraciones.map((integracion:any)=><div key={integracion.id} className="card p-5"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="rounded-lg bg-brand-500/15 p-2.5"><Plug className="h-5 w-5 text-brand-300"/></div><div><h3 className="font-semibold capitalize">{integracion.nombre}</h3><p className="mt-0.5 text-xs text-surface-200/45">{integracion.proveedor} - {integracion.ambiente}</p></div></div><span className={integracion.estado==='configurado'?'badge-green':'badge-yellow'}>{integracion.estado}</span></div><div className="mt-5 space-y-2 text-sm text-surface-200/60"><p>{integracion.endpoint || 'Endpoint por defecto del proveedor'}</p><p>{integracion.tiene_secreto ? 'Credenciales registradas; no se muestran nuevamente' : 'Faltan credenciales de acceso'}</p></div><div className="mt-5 flex items-center justify-between border-t border-white/5 pt-3"><label className="flex items-center gap-2 text-xs text-surface-200/60"><input type="checkbox" checked={integracion.activo} onChange={e=>actualizar.mutate({id:integracion.id,activo:e.target.checked})}/>Activar sincronizacion</label><button className="btn-ghost btn-sm p-2 text-red-300" title="Eliminar" onClick={()=>eliminar.mutate(integracion.id)}><Trash2 className="h-4 w-4"/></button></div></div>)}{integraciones.length===0&&<div className="card col-span-full flex min-h-48 flex-col items-center justify-center text-center"><Link2 className="h-9 w-9 text-surface-200/20"/><p className="mt-3 text-sm text-surface-200/45">No hay integraciones configuradas</p></div>}</div>
    <Modal open={abierto} onClose={()=>setAbierto(false)} title="Nueva integracion ERP" size="md" footer={<div className="flex gap-3"><button className="btn-secondary flex-1" onClick={()=>setAbierto(false)}>Cancelar</button><button className="btn-primary flex-1" disabled={crear.isPending || !form.nombre} onClick={()=>crear.mutate()}>{crear.isPending?'Guardando...':'Guardar integracion'}</button></div>}><div className="space-y-4"><p className="rounded-lg border border-sky-400/20 bg-sky-500/10 p-3 text-xs text-sky-100/80">La activacion requiere credenciales proporcionadas por el ERP. La plataforma guarda la configuracion, sin exponer la clave despues de guardarla.</p><div className="grid grid-cols-2 gap-3"><div><label className="label">Proveedor</label><select className="input" value={form.proveedor} onChange={e=>setForm(p=>({...p,proveedor:e.target.value,nombre:e.target.value==='otro'?'':e.target.value.charAt(0).toUpperCase()+e.target.value.slice(1)}))}>{proveedores.map(proveedor=><option key={proveedor} value={proveedor} className="capitalize">{proveedor}</option>)}</select></div><div><label className="label">Ambiente</label><select className="input" value={form.ambiente} onChange={e=>setForm(p=>({...p,ambiente:e.target.value}))}><option value="pruebas">Pruebas</option><option value="produccion">Produccion</option></select></div></div><div><label className="label">Nombre de conexion</label><input className="input" value={form.nombre} onChange={e=>setForm(p=>({...p,nombre:e.target.value}))}/></div><div><label className="label">Endpoint API</label><input className="input" placeholder="Opcional si se usa el endpoint estandar" value={form.endpoint} onChange={e=>setForm(p=>({...p,endpoint:e.target.value}))}/></div><div><label className="label">Usuario o identificador de cuenta</label><input className="input" value={form.usuario} onChange={e=>setForm(p=>({...p,usuario:e.target.value}))}/></div><div><label className="label">API key o secreto</label><input type="password" className="input" value={form.secreto} onChange={e=>setForm(p=>({...p,secreto:e.target.value}))}/></div><label className="flex items-center gap-2 text-sm text-surface-200/70"><input type="checkbox" checked={form.activo} onChange={e=>setForm(p=>({...p,activo:e.target.checked}))}/>Activar cuando las credenciales esten listas</label></div></Modal>
  </div>
}
