import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ClipboardCheck, PackageCheck, ScanLine, Trash2, Undo2 } from 'lucide-react'
import toast from 'react-hot-toast'
import api from '@/lib/axios'
import Scanner from '@/components/scanner/Scanner'

type Linea = { producto_id:string; codigo:string; nombre:string; cantidad:number; stock:number; costo_unit:string }

export default function ScannerPage({ modo }:{modo:'qr'|'barras'}) {
  const qc=useQueryClient(); const [lote,setLote]=useState<Linea[]>([]); const [tipo,setTipo]=useState<'entrada'|'salida'>('entrada'); const [notas,setNotas]=useState(''); const [ultimo,setUltimo]=useState('')
  const [conteoId,setConteoId]=useState(''); const [nombreConteo,setNombreConteo]=useState(''); const [fecha,setFecha]=useState(''); const [tipoConteo,setTipoConteo]=useState<'general'|'ciclico'>('general'); const [conteosFisicos,setConteosFisicos]=useState<Linea[]>([])
  const {data:productosData=[]}=useQuery({queryKey:['productos-escaner'],queryFn:async()=>{const {data}=await api.get<any>('/productos');return Array.isArray(data.data||data)?data.data||data:[]}})
  const {data:conteosData=[]}=useQuery({queryKey:['conteos-inventario'],enabled:modo==='qr',queryFn:async()=>{const {data}=await api.get<any>('/conteos');return Array.isArray(data.data||data)?data.data||data:[]}})
  const productos:any[]=productosData; const conteos:any[]=conteosData
  const agregarAlLote=(codigo:string, destino:'lote'|'conteo')=>{const producto=productos.find((p:any)=>String(p.codigo||'').trim().toLowerCase()===codigo.trim().toLowerCase());if(!producto){toast.error(`Producto no registrado: ${codigo}`);return}const setter=destino==='lote'?setLote:setConteosFisicos;setter(actual=>{const existe=actual.find(item=>item.producto_id===producto.id);if(destino==='lote'&&tipo==='salida'&&Number(existe?.cantidad||0)+1>Number(producto.stock_actual||0)){toast.error(`Stock insuficiente: ${producto.nombre}`);return actual}return existe?actual.map(item=>item.producto_id===producto.id?{...item,cantidad:item.cantidad+1}:item):[...actual,{producto_id:producto.id,codigo:String(producto.codigo||codigo),nombre:producto.nombre,cantidad:1,stock:Number(producto.stock_actual||0),costo_unit:String(Number(producto.precio_costo||0))}]});setUltimo(producto.nombre)}
  const guardarLote=useMutation({mutationFn:()=>api.post('/inventario',{items:lote,tipo,notas}),onSuccess:()=>{qc.invalidateQueries({queryKey:['inventario']});qc.invalidateQueries({queryKey:['dashboard-stats']});setLote([]);setNotas('');toast.success('Lote guardado correctamente')},onError:(e:any)=>toast.error(e?.response?.data?.msg||'No se pudo guardar el lote')})
  const crearConteo=useMutation({mutationFn:()=>api.post('/conteos',{accion:'crear',nombre:nombreConteo,tipo:tipoConteo,programado_para:fecha||undefined,iniciar:!fecha}),onSuccess:(r:any)=>{qc.invalidateQueries({queryKey:['conteos-inventario']});if(r.data?.data?.estado==='abierto')setConteoId(r.data.data.id);setNombreConteo('');setFecha('');toast.success('Conteo creado')},onError:(e:any)=>toast.error(e?.response?.data?.msg||'No se pudo crear el conteo')})
  const iniciar=useMutation({mutationFn:(id:string)=>api.post('/conteos',{accion:'iniciar',conteo_id:id}),onSuccess:(_:any,id)=>{qc.invalidateQueries({queryKey:['conteos-inventario']});setConteoId(id)}})
  const guardarConteo=useMutation({mutationFn:async()=>{for(const item of conteosFisicos)await api.post('/conteos',{accion:'registrar',conteo_id:conteoId,producto_id:item.producto_id,cantidad:item.cantidad})},onSuccess:()=>{qc.invalidateQueries({queryKey:['conteos-inventario']});setConteosFisicos([]);toast.success('Borrador de conteo guardado')},onError:(e:any)=>toast.error(e?.response?.data?.msg||'No se pudo guardar el conteo')})
  const cerrar=useMutation({mutationFn:(id:string)=>api.post('/conteos',{accion:'cerrar',conteo_id:id}),onSuccess:()=>{qc.invalidateQueries({queryKey:['conteos-inventario']});qc.invalidateQueries({queryKey:['inventario']});setConteoId('');setConteosFisicos([]);toast.success('Conteo conciliado')},onError:(e:any)=>toast.error(e?.response?.data?.msg||'No se pudo cerrar el conteo')})
  const resumen=useMemo(()=>({referencias:lote.length,unidades:lote.reduce((s,i)=>s+i.cantidad,0)}),[lote]); const activos=conteos.filter(c=>c.estado==='abierto');const seleccionado=conteos.find(c=>c.id===conteoId)
  const lista = (items:Linea[], setItems:React.Dispatch<React.SetStateAction<Linea[]>>) => (
    <div className="card overflow-hidden"><div className="border-b border-white/10 p-4"><h2 className="font-semibold">Productos escaneados</h2><p className="mt-1 text-sm text-surface-200/60">{items.length} referencias · {items.reduce((s,i)=>s+i.cantidad,0)} unidades</p></div>
      {items.length===0 ? <p className="p-8 text-center text-surface-200/45">El lector está listo. Escanea productos consecutivamente.</p> : <div className="divide-y divide-white/10">
        {items.map(item => (
          <div key={item.producto_id} className="flex flex-wrap items-center gap-3 p-3">
            <div className="min-w-44 flex-1">
              <p className="font-medium">{item.nombre}</p>
              <p className="font-mono text-xs text-surface-200/50">{item.codigo}</p>
              {tipo==='salida' && <p className="text-xs text-amber-200">Disponible: {item.stock} · Restante: {item.stock - item.cantidad}</p>}
            </div>
            <div className="flex items-center gap-2">
              <button className="btn-secondary h-9 w-9 p-0" onClick={() => setItems(actual => actual.map(linea => linea.producto_id === item.producto_id ? { ...linea, cantidad: Math.max(1, linea.cantidad - 1) } : linea))}>-</button>
              <input className="input h-9 w-20 text-center" type="number" min="1" value={item.cantidad} onChange={event => setItems(actual => actual.map(linea => linea.producto_id === item.producto_id ? { ...linea, cantidad: Math.max(1, Number(event.target.value) || 1) } : linea))}/>
              <button className="btn-secondary h-9 w-9 p-0" onClick={() => setItems(actual => actual.map(linea => linea.producto_id === item.producto_id ? { ...linea, cantidad: linea.cantidad + 1 } : linea))}>+</button>
              <button className="btn-ghost h-9 w-9 p-0 text-red-300" onClick={() => setItems(actual => actual.filter(linea => linea.producto_id !== item.producto_id))}><Trash2 className="h-4 w-4"/></button>
            </div>
          </div>
        ))}
      </div>}
    </div>
  )
  if(modo==='barras')return <div className="mx-auto max-w-4xl space-y-5"><div className="page-header"><div><h1 className="page-title">{tipo==='entrada'?'Entrada de mercancía':'Salida de mercancía'}</h1><p className="page-subtitle">Escanea todos los productos; el inventario cambia una sola vez al guardar el lote.</p></div><select className="input w-56" value={tipo} onChange={e=>setTipo(e.target.value as any)}><option value="entrada">Entrada de mercancía</option><option value="salida">Salida de mercancía</option></select></div><div className="card p-4"><Scanner modo="barras" continuo onDetectar={codigo=>agregarAlLote(codigo,'lote')}/>{ultimo&&<p className="mt-3 text-sm text-emerald-300">Último producto: {ultimo}</p>}</div>{lista(lote,setLote)}<div className="card space-y-3 p-4"><input className="input" value={notas} onChange={e=>setNotas(e.target.value)} placeholder="Notas del lote (opcional)"/><div className="flex flex-wrap justify-between gap-3"><button className="btn-secondary" disabled={!lote.length} onClick={()=>setLote(a=>a.slice(0,-1))}><Undo2 className="h-4 w-4"/>Deshacer última lectura</button><button className="btn-primary" disabled={!lote.length||guardarLote.isPending} onClick={()=>{if(window.confirm(`Confirmar ${tipo}: ${resumen.referencias} referencias y ${resumen.unidades} unidades`))guardarLote.mutate()}}><PackageCheck className="h-4 w-4"/>{guardarLote.isPending?'Guardando...':`Guardar ${tipo}`}</button></div></div></div>
  return <div className="mx-auto max-w-4xl space-y-5"><div className="page-header"><div><h1 className="page-title">Conteos generales y cíclicos</h1><p className="page-subtitle">Programa, escanea cantidades físicas y concilia solo al cerrar el conteo.</p></div></div><div className="card grid gap-3 p-4 md:grid-cols-4"><input className="input md:col-span-2" value={nombreConteo} onChange={e=>setNombreConteo(e.target.value)} placeholder="Nombre del conteo"/><select className="input" value={tipoConteo} onChange={e=>setTipoConteo(e.target.value as any)}><option value="general">General</option><option value="ciclico">Cíclico</option></select><input className="input" type="date" value={fecha} onChange={e=>setFecha(e.target.value)}/><button className="btn-primary md:col-span-4" disabled={!nombreConteo||crearConteo.isPending} onClick={()=>crearConteo.mutate()}><ClipboardCheck className="h-4 w-4"/>{fecha?'Programar conteo':'Crear e iniciar conteo'}</button></div><div className="card p-4"><label className="label">Conteo abierto</label><div className="flex gap-2"><select className="input flex-1" value={conteoId} onChange={e=>setConteoId(e.target.value)}><option value="">Selecciona un conteo</option>{activos.map(item=><option key={item.id} value={item.id}>{item.nombre} ({item.productos_contados} registrados)</option>)}</select>{conteos.filter(c=>c.estado==='programado').map(item=><button key={item.id} className="btn-secondary" onClick={()=>iniciar.mutate(item.id)}>Iniciar</button>)}</div></div>{seleccionado&&<><div className="card p-4"><Scanner modo="qr" continuo onDetectar={codigo=>agregarAlLote(codigo,'conteo')}/></div>{lista(conteosFisicos,setConteosFisicos)}<div className="flex flex-wrap justify-end gap-3"><button className="btn-secondary" disabled={!conteosFisicos.length||guardarConteo.isPending} onClick={()=>guardarConteo.mutate()}>Guardar borrador</button><button className="btn-danger" disabled={cerrar.isPending} onClick={()=>{if(window.confirm('El cierre ajustará el inventario a las cantidades físicas registradas.'))cerrar.mutate(seleccionado.id)}}>Finalizar y conciliar conteo</button></div></>}{!seleccionado&&<p className="card p-8 text-center text-surface-200/55">Crea o inicia un conteo para habilitar el lector QR.</p>}</div>
}
