import { useQuery } from '@tanstack/react-query'
import { CalendarDays, Gift } from 'lucide-react'
import { useParams } from 'react-router-dom'
import api from '@/lib/axios'
import { formatCurrency, formatDate } from '@/lib/utils'
import { PageLoader } from '@/components/ui/Spinner'

export default function MenuDigitalPage() {
  const { empresa, mesa } = useParams<{empresa:string;mesa:string}>()
  const {data,isLoading,error}=useQuery({queryKey:['menu-publico',empresa,mesa],queryFn:async()=>{const {data}=await api.get(`/menu/${empresa}/${encodeURIComponent(mesa||'')}`);return data.data},enabled:!!empresa&&!!mesa})
  if(isLoading)return <div className="flex min-h-screen items-center justify-center bg-slate-950"><PageLoader/></div>
  if(error||!data)return <div className="flex min-h-screen items-center justify-center bg-slate-950 p-6 text-center text-white">Este código QR no corresponde a una mesa activa.</div>
  return <main className="min-h-screen bg-slate-950 text-slate-100"><header className="sticky top-0 z-10 border-b border-white/10 bg-slate-950/95 p-5 backdrop-blur"><div className="mx-auto flex max-w-3xl items-center gap-3">{data.empresa.logo_url&&<img src={data.empresa.logo_url} alt="Logo del negocio" className="h-10 w-10 rounded-lg object-cover"/>}<div><h1 className="font-bold">{data.empresa.nombre}</h1><p className="text-sm text-slate-400">Menú digital · Mesa {data.mesa.numero}{data.mesa.nombre?` · ${data.mesa.nombre}`:''}</p></div></div></header><section className="mx-auto max-w-3xl space-y-6 p-4 sm:p-6">{data.eventos?.length>0&&<div><div className="mb-3 flex items-center gap-2"><Gift className="h-5 w-5 text-amber-300"/><h2 className="font-semibold">Eventos y promociones</h2></div><div className="flex snap-x gap-3 overflow-x-auto pb-2">{data.eventos.map((evento:any)=><article key={evento.id} className="w-64 shrink-0 snap-start overflow-hidden rounded-xl border border-amber-300/20 bg-slate-900">{evento.imagen_url&&<img src={evento.imagen_url} alt={evento.titulo} className="h-28 w-full object-cover"/>}<div className="p-3"><span className="text-xs font-medium uppercase text-amber-300">{evento.tipo}</span><h3 className="mt-1 font-semibold">{evento.titulo}</h3>{evento.descripcion&&<p className="mt-1 text-sm text-slate-400">{evento.descripcion}</p>}{evento.fecha_inicio&&<p className="mt-3 flex items-center gap-1 text-xs text-slate-500"><CalendarDays className="h-3.5 w-3.5"/>{formatDate(evento.fecha_inicio,'dd/MM/yyyy HH:mm')}</p>}</div></article>)}</div></div>}<div><h2 className="mb-3 font-semibold">Menú</h2><div className="grid gap-3 sm:grid-cols-2">{data.productos.map((p:any)=><article key={p.id} className="flex gap-3 rounded-xl border border-white/10 bg-slate-900 p-3">{p.imagen_url?<img src={p.imagen_url} alt={p.nombre} className="h-20 w-20 rounded-lg object-cover"/>:<div className="h-20 w-20 rounded-lg bg-brand-600/20"/>}<div className="min-w-0 flex-1"><p className="font-semibold">{p.nombre}</p><p className="mt-1 line-clamp-2 text-xs text-slate-400">{p.descripcion||p.categoria||'Producto disponible'}</p><p className="mt-2 font-bold text-brand-300">{formatCurrency(p.precio_venta)}</p></div></article>)}</div>{data.productos.length===0&&<p className="py-16 text-center text-slate-400">El menú aún no tiene productos disponibles.</p>}</div></section></main>
}
