import { v4 as uuid } from 'uuid'
import { query, queryOne } from '../_db.js'
import { authenticate, cors } from '../_auth.js'
import { ensureRestaurantSchema, esRestaurante, movimientoIngrediente, recalcularRecetasIngrediente } from './_restaurante.js'

export default async function handler(req:any,res:any) {
  cors(res); if(req.method==='OPTIONS') return res.status(200).end(); const auth=await authenticate(req,res); if(!auth?.empresa_id)return
  await ensureRestaurantSchema(); const eid=auth.empresa_id; if(!(await esRestaurante(eid)))return res.status(403).json({ok:false,msg:'Modulo exclusivo para restaurantes'})
  if(req.method==='GET'){const rows=await query(`SELECT c.*,COUNT(ci.id)::int as items FROM compras_ingredientes c LEFT JOIN compra_ingrediente_items ci ON ci.compra_id=c.id WHERE c.empresa_id=$1 GROUP BY c.id ORDER BY c.fecha_compra DESC,c.created_at DESC LIMIT 300`,[eid]);return res.status(200).json({ok:true,data:rows})}
  if(req.method!=='POST')return res.status(405).end(); const b=req.body||{}; const items=Array.isArray(b.items)?b.items:[]; if(!items.length)return res.status(400).json({ok:false,msg:'Agrega al menos un ingrediente'})
  const compraId=uuid(); let subtotal=0, impuestos=Number(b.impuestos)||0, descuentos=Number(b.descuentos)||0, transporte=Number(b.transporte)||0
  const calculados:any[]=[]
  for(const item of items){const ingrediente=await queryOne(`SELECT * FROM ingredientes WHERE id=$1 AND empresa_id=$2 AND activo=true`,[item.ingrediente_id,eid]) as any;if(!ingrediente)return res.status(400).json({ok:false,msg:'Ingrediente invalido'});const recibida=Number(item.cantidad_recibida ?? item.cantidad_compra)*Math.max(0.0001,Number(item.factor_conversion ?? ingrediente.factor_conversion)||1);const costo=Math.max(0,Number(item.precio_unitario)||0)*Math.max(0,Number(item.cantidad_compra)||0)+Number(item.costo_adicional)||0-Number(item.descuentos)||0+Number(item.impuestos)||0;if(recibida<=0||costo<0)return res.status(400).json({ok:false,msg:'Cantidad o costo invalido'});subtotal+=costo;calculados.push({item,ingrediente,recibida,costo})}
  const total=Math.max(0,subtotal+impuestos+transporte-descuentos); await query(`INSERT INTO compras_ingredientes (id,empresa_id,proveedor,numero_factura,fecha_compra,subtotal,impuestos,descuentos,transporte,total,observaciones,usuario_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[compraId,eid,b.proveedor||null,b.numero_factura||null,b.fecha_compra||new Date().toISOString().slice(0,10),subtotal,impuestos,descuentos,transporte,total,b.observaciones||null,auth.id])
  for(const c of calculados){const previo=Number(c.ingrediente.stock_actual)||0;const costoPrevio=Number(c.ingrediente.costo_unitario)||0;const costoNuevo=c.costo/c.recibida;const promedio=(previo*costoPrevio+c.recibida*costoNuevo)/(previo+c.recibida);await query(`UPDATE ingredientes SET costo_unitario=$1 WHERE id=$2 AND empresa_id=$3`,[promedio,c.ingrediente.id,eid]);await query(`INSERT INTO ingrediente_costos (id,empresa_id,ingrediente_id,costo_anterior,costo_nuevo,motivo) VALUES ($1,$2,$3,$4,$5,'compra')`,[uuid(),eid,c.ingrediente.id,costoPrevio,promedio]);await query(`INSERT INTO compra_ingrediente_items (id,compra_id,empresa_id,ingrediente_id,cantidad_compra,factor_conversion,cantidad_recibida,precio_unitario_compra,impuestos,descuentos,costo_adicional,costo_total,lote,vencimiento) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,[uuid(),compraId,eid,c.ingrediente.id,Number(c.item.cantidad_compra),Number(c.item.factor_conversion ?? c.ingrediente.factor_conversion)||1,c.recibida,Number(c.item.precio_unitario)||0,Number(c.item.impuestos)||0,Number(c.item.descuentos)||0,Number(c.item.costo_adicional)||0,c.costo,c.item.lote||null,c.item.vencimiento||null]);await movimientoIngrediente({empresaId:eid,ingredienteId:c.ingrediente.id,usuarioId:auth.id,tipo:'compra',entrada:c.recibida,proveedor:b.proveedor,documento:b.numero_factura,observaciones:b.observaciones});await recalcularRecetasIngrediente(c.ingrediente.id,eid)}
  return res.status(201).json({ok:true,data:{id:compraId,total}})
}
